# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: facewiseLog
subtitle: ''
description: ''
keywords:
author: Yonghyun Kim
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://facewise.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/facewise/facewise.github.io.git
  branch: main

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next 

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------
theme_config:
  # Allow to cache content generation.
  cache:
    enable: false
    
  # Remove unnecessary files after hexo generate.
  minify: true
    
  # Schemes
  scheme: Mist
  #scheme: Pisces
  #scheme: Gemini
  
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    Github: https://github.com/facewise || fab fa-github
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat
    
  favicon:
    small: /images/favicon-16x16-next.png
    medium: /images/favicon-32x32-next.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg
  menu_settings:
    icons: true
    badges: false
      
  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.js.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------
  sidebar:
    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post
    
  # ---------------------------------------------------------------
  # Footer Settings
  # See: https://theme-next.js.org/docs/theme-settings/footer
  # ---------------------------------------------------------------

  # Show multilingual switcher in footer.
  language_switcher: false

  footer:
    # Specify the year when the site was setup. If not defined, current year will be used.
    #since: 2021

    # Icon between year and copyright info.
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: fa fa-heart
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#ff0000"

    # If not defined, `author` from Hexo `_config.yml` will be used.
    # Set to `false` to disable the copyright statement.
    copyright:

    # Powered by Hexo & NexT
    powered: false
  
  social:
    GitHub: https://github.com/facewise || fab fa-github
    E-Mail: mailto:dydgus.k@gmail.com || fa fa-envelope
  
  social_icons:
    enable: true
    icons_only: true
    transition: false
    
  # ---------------------------------------------------------------
  # Font Settings
  # ---------------------------------------------------------------
  # Find fonts on Google Fonts (https://fonts.google.com)
  # All fonts set here will have the following styles:
  #   light | light italic | normal | normal italic | bold | bold italic
  # Be aware that setting too much fonts will cause site running slowly
  # ---------------------------------------------------------------
  # Web Safe fonts are recommended for `global` (and `title`):
  # Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
  # ---------------------------------------------------------------

  font:
    enable: true

    # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
    host: 

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: IBM Plex Sans KR
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family:
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family:
      size:

    # Font settings for posts (.post-body).
    posts:
      external: true
      family:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family:
  
  github_banner:
    enable: true
    permalink: https://github.com/facewise
  
  motion:
    enable: false
